### PR TITLE
fix jce installation on windows

### PR DESCRIPTION
**Pull request by axos88**

### CODE REVIEW

**Comment by axos88** [comment]
ping

**Comment by axos88** [comment]
@erichelgeson

**Comment by erichelgeson** [comment]
@axos88 Thanks for the contribution but Travis says the tests for win jce are failing, could you address that? Also please do not bump versions in PR's.

**Comment by axos88** [comment]
Sorry, i did not mean to bump the version. Checking travis now

**Comment by erichelgeson** [comment]
Merged in master https://github.com/agileorbit-cookbooks/java/commit/06f752b6cacf3a167649183ef2b410e14791e524, travis release shortly

**Comment by axos88** [comment]
thanks.

**Pull request closed without merging**
