### PR TITLE
Extract files to temp directory instead of Chef::Config['file_cache_path']

### PR DESCRIPTION
**Pull request by tknerr**
Extract the file contents of the downloaded java archive into the system's temp directory, rather than `Chef::Config['file_cache_path']`.

This is for two reasons:
1. currently the Chef run fails when the `Chef::Config['file_cache_path']` is located on a VirtualBox shared folder (e.g. when using [vagrant-cachier](https://github.com/fgrehm/vagrant-cachier)). It's not immediately obvious from the logs but the root cause is [this VirtualBox restriction](http://superuser.com/a/446908) 
2. we may want to keep the `Chef::Config['file_cache_path']` clean (i.e. we don't need to cache both the archive AND it's extracted contents)

### CODE REVIEW

**Comment by tknerr** [comment]
Btw these are the errors I get otherwise

Output from the chef run:
```
==> elastic-test: Recipe: java::oracle
==> elastic-test:
==> elastic-test: * apt_package[tar] action install
==> elastic-test:  (up to date)
==> elastic-test:   * java_ark[jdk] action install
==> elastic-test: [2015-12-04T13:50:10+00:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.8.0_51
==> elastic-test:     - create dir /usr/lib/jvm and change owner to root:root
==> elastic-test: [2015-12-04T13:50:23+00:00] FATAL: Failed to extract file jdk-8u51-linux-x64.tar.gz!
==> elastic-test:
==> elastic-test:     ================================================================================
==> elastic-test:     Error executing action `install` on resource 'java_ark[jdk]'
==> elastic-test:     ================================================================================
==> elastic-test:
==> elastic-test:     SystemExit
==> elastic-test:     ----------
==> elastic-test:     exit
==> elastic-test:
==> elastic-test:     Cookbook Trace:
==> elastic-test:     ---------------
==> elastic-test:     /var/chef/cache/cookbooks/java/providers/ark.rb:164:in `block (2 levels) in class_from_file'
==> elastic-test:     /var/chef/cache/cookbooks/java/providers/ark.rb:142:in `block in class_from_file'
==> elastic-test:
==> elastic-test:     Resource Declaration:
==> elastic-test:     ---------------------
==> elastic-test:     # In /var/chef/cache/cookbooks/java/recipes/oracle.rb
==> elastic-test:
==> elastic-test:      55: java_ark "jdk" do
==> elastic-test:      56:   url tarball_url
==> elastic-test:      57:   default node['java']['set_default']
==> elastic-test:      58:   checksum tarball_checksum
==> elastic-test:      59:   app_home java_home
==> elastic-test:      60:   bin_cmds bin_cmds
==> elastic-test:      61:   alternatives_priority node['java']['alternatives_priority']
==> elastic-test:      62:   retries node['java']['ark_retries']
==> elastic-test:      63:   retry_delay node['java']['ark_retry_delay']
==> elastic-test:      64:   connect_timeout node['java']['ark_timeout']
==> elastic-test:      65:   use_alt_suffix node['java']['use_alt_suffix']
==> elastic-test:      66:   reset_alternatives node['java']['reset_alternatives']
==> elastic-test:      67:   action :install
==> elastic-test:      68: end
==> elastic-test:      69:
==> elastic-test:
==> elastic-test:     Compiled Resource:
==> elastic-test:     ------------------
==> elastic-test:     # Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:55:in `from_file'
==> elastic-test:
==> elastic-test:     java_ark("jdk") do
==> elastic-test:       action [:install]
==> elastic-test:       supports {:report=>true, :exception=>true}
==> elastic-test:       retries 0
==> elastic-test:       retry_delay 2
==> elastic-test:       default_guard_interpreter :default
==> elastic-test:       declared_type :java_ark
==> elastic-test:       cookbook_name "java"
==> elastic-test:       recipe_name "oracle"
==> elastic-test:       url "http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-x64.tar.gz"
==> elastic-test:       default true
==> elastic-test:       checksum "b34ff02c5d98b6f372288c17e96c51cf"
==> elastic-test:       app_home "/usr/lib/jvm/java-8-oracle-amd64"
==> elastic-test:       bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jdeps", "jhat", "jinfo", "jjs", "jmap", "jmc", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
==> elastic-test:       alternatives_priority 1062
==> elastic-test:       connect_timeout 600
==> elastic-test:       use_alt_suffix true
==> elastic-test:       reset_alternatives true
==> elastic-test:       owner "root"
==> elastic-test:       app_home_mode 493
==> elastic-test:     end
==> elastic-test:
==> elastic-test:
==> elastic-test: [2015-12-04T13:50:23+00:00] INFO: Running queued delayed notifications before re-raising exception
==> elastic-test:
==> elastic-test: Running handlers:
==> elastic-test: [2015-12-04T13:50:23+00:00] ERROR: Running exception handlers
==> elastic-test: Running handlers complete
==> elastic-test:
==> elastic-test: [2015-12-04T13:50:23+00:00] ERROR: Exception handlers complete
==> elastic-test: Chef Client failed. 9 resources updated in 230.704479382 seconds
==> elastic-test: [2015-12-04T13:50:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> elastic-test: [2015-12-04T13:50:24+00:00] ERROR: java_ark[jdk] (java::oracle line 55) had an error: SystemExit: exit
==> elastic-test: [2015-12-04T13:50:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

And in `/var/chef/stacktrace.out`:
```
Generated at 2015-12-04 13:50:23 +0000
SystemExit: java_ark[jdk] (java::oracle line 55) had an error: SystemExit: exit
/opt/chef/embedded/apps/chef/lib/chef/application.rb:404:in `exit'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:404:in `fatal!'
/var/chef/cache/cookbooks/java/providers/ark.rb:164:in `block (2 levels) in class_from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
/var/chef/cache/cookbooks/java/providers/ark.rb:142:in `block in class_from_file'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:160:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:160:in `block in action'
Generated at 2015-12-04 13:50:23 +0000
SystemExit: java_ark[jdk] (java::oracle line 55) had an error: SystemExit: exit
/opt/chef/embedded/apps/chef/lib/chef/application.rb:404:in `exit'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:404:in `fatal!'
/var/chef/cache/cookbooks/java/providers/ark.rb:164:in `block (2 levels) in class_from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
/var/chef/cache/cookbooks/java/providers/ark.rb:142:in `block in class_from_file'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:160:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:160:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:55:in `load'
/usr/bin/chef-client:55:in `<main>'
```

@erichelgeson mind reviewing the code changes in this PR?

Unfortunately the travis is failing on master since a few commits, so it errors in this PR too :-/

Anyway the unit tests passed when I ran them locally. I didn't have the resources to run the whole kitchenci test suite though (and don't see their current build status as they are not running on travis)

**Comment by tknerr** [comment]
rebased against master + force push to re-trigger the travis-ci build

@erichelgeson any chance to review this PR and include it in an upcoming release? 

Btw: is the full kitchenci test suite actually run somewhere else (internal jenkins or the like)?

**Comment by tknerr** [comment]
travis says it's green at least ;-)

**Comment by erichelgeson** [comment]
Over a year later, sorry for the slow response - If you still would like this please rebase off master I'll test and merge. Thanks! (Closing for now, but just to clean up old tickets)

**Comment by tknerr** [comment]
@erichelgeson yes, definitely interested in that. Will try to get a rebased version ready for you to review. Hopefully tomorrow.

**Pull request closed without merging**
