### PR TITLE
add java_certificate LWRP from java-libraries cookbook

### PR DESCRIPTION
**Pull request by spion06**

### CODE REVIEW

**Comment by spion06** [comment]
The (java-libraries)[https://github.com/agileorbit-cookbooks/java-libraries] doesn't seem to be getting much love so submitting the PR. Working on fixing up rubocop

**Comment by spion06** [comment]
rubocop and foodcritic are behaving now. let me know if you want to see any additional tests

**Comment by erichelgeson** [comment]
Hi!

What are the actual changes between the lwrp in `java_certificate` and here? Since that never went past the 1 lwrp maybe it makes sense to add it into "core" java cookbook. I'll run the tests tomorrow and take a look.

**Comment by spion06** [comment]
sorry about the slow response here. There's no functional changes from the java-libraries cookbook since https://github.com/agileorbit-cookbooks/java-libraries/pull/10 was merged. It was simply moving my changes from there into here and fixing up the foodcritic/rubocop issues

**Comment by erichelgeson** [comment]
Hi @spion06 - was looking to release this today but ran into an issue with these tests - it looks like the fingerprint asserted is not what is actually in the test:
```
➜  java git:(master) kitchen login oracle-8-centos-71
Last login: Tue Dec  6 14:08:27 2016 from 10.0.2.2
[vagrant@oracle-8-centos-71 ~]$  source /etc/profile.d/jdk.sh
[vagrant@oracle-8-centos-71 ~]$ $JAVA_HOME/bin/keytool -list -storepass changeit -keystore $JAVA_HOME/jre/lib/security/cacerts -alias java_certificate_test
java_certificate_test, Dec 6, 2016, trustedCertEntry,
Certificate fingerprint (SHA1): 9D:9E:EA:E6:5F:D2:C8:34:93:6E:5C:65:EE:00:46:A9:CD:E4:F1:83
```
Just wanted to make sure this is actually what should be asserted and not an issue.

**Comment by spion06** [comment]
i must have copied the wrong version of the cert over it looks like :( sorry about that!

**Pull request merged**
