### PR TITLE
Remove unnecessary apt update

### LINKED ISSUE #406: Don't run `apt update` in common cookbooks
See Chef developer's opinion here: https://github.com/chef-cookbooks/runit/pull/214#issuecomment-286858834:
> Apt updates are something that need to be managed by the consumer of the cookbook themselves. We end up with multiple cookbooks each trying to do apt-updates and it's a bit of a mess.

### PR DESCRIPTION
**Pull request by grv87**
`apt_repository` should update apt package cache by itself

Closes #406

### CODE REVIEW

**Comment by erichelgeson** [comment]
I just tried 6efd18f locally and it failed. It looks like FC023 is deprecated now so adding `~FC023` to `.foodcritic` would be fine instead. Also test in kitchen - looks good.

**Comment by grv87** [comment]
I haven't reach to kitchen yet, but I've understood that FC023 should be turned off. Attempt to comply to it doesn't work.

**Comment by erichelgeson** [comment]
NP, I took care of the integration testing, saw it do the apt-get update when the new ppa was added. Thanks for the contribution and bearing with me!

**Comment by grv87** [comment]
@erichelgeson, thanks to you for cooperation!

**Pull request merged**
