### PR TITLE
Precises fixes

### PR DESCRIPTION
**Pull request by secondsun**
I was trying to install OpenJDK Java 8 on a Precise image and I needed to make these changes to get it to work.

### CODE REVIEW

**Comment by erichelgeson** [comment]
I added 12.04.4 into kitchen, but I do not see any issues with 12.04.4 on master without this pr - 
```
       Chef Client finished, 19/32 resources updated in 02 minutes 36 seconds
       Finished converging <openjdk-8-ubuntu-1204> (3m1.65s).
-----> Setting up <openjdk-8-ubuntu-1204>...
       Finished setting up <openjdk-8-ubuntu-1204> (0m0.00s).
-----> Verifying <openjdk-8-ubuntu-1204>...
       Preparing files for transfer
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       Successfully installed thor-0.19.0
Fetching: busser-0.7.1.gem (100%)
       Successfully installed busser-0.7.1
       2 gems installed
       Installing Busser plugins: busser-bats
       Plugin bats installed (version 0.3.0)
-----> Running postinstall for bats plugin
       Installed Bats to /tmp/verifier/vendor/bats/bin/bats
       Suite path directory /tmp/verifier/suites does not exist, skipping.
       Transferring files to <openjdk-8-ubuntu-1204>
-----> Running bats test suite
 ✓ installs the correct version of the jdk
 ✓ properly sets JAVA_HOME environment variable
 ✓ properly links jar

       3 tests, 0 failures
       Finished verifying <openjdk-8-ubuntu-1204> (0m6.15s).
-----> Kitchen is finished. (3m44.12s)
```

**Comment by secondsun** [comment]
Odd.  It may be that the image corporate has us using has something different.  I the problem I was running into was that when I tried to load openjdk apt would fail because the ppa file was missing the main repository declaration.

**Comment by erichelgeson** [comment]
hmm, could be. Could remove everything but `components ["main"]`, since it is what is the default in that ppa and shouldn't affect anything else, if that helps in your case. If not we can just leave it as is.

**Comment by erichelgeson** [comment]
Please open another PR if you find the root cause and it requires a change.

**Pull request closed without merging**
