### PR TITLE
Changes to prevent re-execution of resource creating file jdk.sh

### PR DESCRIPTION
**Pull request by bijugs**
In the current code the resource [``file '/etc/profile.d/jdk.sh'``](https://github.com/agileorbit-cookbooks/java/blob/c1952dfda48c8fe674cd9124a5f5b2158a47ce7c/recipes/set_java_home.rb#L30-L33) gets executed on every run even when there is no change. The PR is to prevent this unnecessary execution by changing it into a ``template`` resource.

### CODE REVIEW

**Comment by bijugs** [comment]
Thanks @erichelgeson for merging the PR. Is there a schedule by when these changes will get reflected when someone pulls the cookbook from ``supermarket``.

**Comment by erichelgeson** [comment]
Should be automatically pushed when the commit was tagged, but wasnt - https://travis-ci.org/agileorbit-cookbooks/java#L584 Travis says it's not a tagged commit, though it is tagged.

**Comment by bijugs** [comment]
FYI. Did a ``knife cookbook site download java --config .chef/knife.rb`` and looked at the code. The changes to ``recipes/set_java_home.rb`` is not there yet.

**Comment by erichelgeson** [comment]
Yes, as stated the auto-deploy did not go - I've manually uploaded 1.40.0

**Comment by bijugs** [comment]
Thanks a lot @erichelgeson .

**Pull request merged**
