### PR TITLE
Ibm s390x arch

### PR DESCRIPTION
**Pull request by zamedic**
We are running ZLinux using the S390X chipset architecture. The only JVM that runs on this architecture is the official IBM SDK compiled specifically for the S390X chipset. 

The change I made checks is the architecture starts with s390, and if so, sets the IBM SDK as the default.

### CODE REVIEW

**Comment by erichelgeson** [comment]
Hi @zamedic, thanks for the contribution! I have no way to test this (no mainframes laying around) but it looks simple enough.

Can you fix the foodcritic issue? Also please revert the version number change, that happens as part of the release process.

**Comment by zamedic** [comment]
@erichelgeson Thank you. I have made the changes as requested. 

The new Food Critic errors, are those related to anything I have done?

**Comment by erichelgeson** [comment]
I rebased & squashed your commits and they pass. I see you merged master in at some point, which maybe is what caused the issue. v1.44.0 is on it's way to be published via travis in a few min. 

810da6cc1a45ef3fb4d5c7f1bd2275fd6d7492b7

**Comment by erichelgeson** [comment]
I've also setup a cron job in travis if no builds have happened in 24 hours to build to catch these issues when chef-dk updates (not wait for someone to open a PR and have unexpected issues :)

**Pull request closed without merging**
